### ISSUE TITLE
How to evaluate for a limited range of experiment 

### ISSUE THREAD

**Issue by ansabsheikh9** [traveller59/kitti-object-eval-python#2]
Hi,
Thank you for sharing your code,
if I have detection boxes in a limited range, for example, I restricted my range to 0 - 50 meters in the x-direction, so while evaluation, do I have to remove boxes in ground truth manually after this range?
Thanks In advance
Best Regards,
Ansab

**Comment by johleh** [comment]
@ansabsheikh9
from my understanding :  yes. clean up the ground truth labels. delete all objects not within the limited range. without deleting these lines in the labels you will get additional false negatives, your recall suffers and the evaluation is not accurate.

**Comment by ansabsheikh9** [comment]
thank you for your prompt reply.
